include environet source as submodule, fewer commands to be run, optional .env file

diff --git a/environet b/environet
--- a/environet
+++ b/environet
@@ -1,7 +1,5 @@
 #!/bin/bash
 
-ENV_FILE=".env"
-
 # Determine compose file location and php service name based on the first argument, which should be 'data', 'dist' or 'doc'
 case $1 in
   data)
@@ -25,20 +23,40 @@ then
   exit 1
 fi
 
+start_services () {
+  echo "starting project $1"
+  docker-compose -p "$1" -f $COMPOSE_FILE up -d
+
+  if [[ $? != 0 ]]
+  then
+    echo
+    echo -e "\e[31mCould not start services"
+    exit 1
+  fi
+}
+
 # If $2 is up, do not forward command to the container, just start the services
 if [[ $2 = "up" ]]
 then
-  docker-compose --env-file $ENV_FILE -f $COMPOSE_FILE up -d
+  start_services $1
   exit 0
 fi
 
 # If $2 is down, do not forward command to the container, just stop the services
 if [[ $2 = "down" ]]
 then
-  docker-compose --env-file $ENV_FILE -f $COMPOSE_FILE down
+  docker-compose -p "$1" -f $COMPOSE_FILE down
   exit 0
 fi
 
-# TODO Pass all arguments. $@ doesn't seem to work...
-docker-compose --env-file $ENV_FILE -f $COMPOSE_FILE exec $SERVICE_NAME bash -c "/var/www/html/bin/environet $1 $2 $3 $4"
+start_services $1
 
+# TODO Pass all arguments. $@ doesn't seem to work...
+docker-compose -p "$1" -f $COMPOSE_FILE exec $SERVICE_NAME bash -c "/var/www/html/bin/environet $1 $2 $3 $4"
+
+if [[ $? != 0 ]]
+then
+  echo
+  echo -e "\e[31mAn error occured while running your command. There may be additional information above." >&2
+  exit 1
+fi
